name: Build Custom Bazzite GNOME
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: '${{ github.actor }}'

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: bazzite-gnome-bc250-unlocked
          tags: latest
          containerfiles: |
            ./Containerfile

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ env.OWNER_LC }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
